PIW4/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as authentification_views

from PIW4.views import AccueilView, AdministrationView
from restaurants.views import MesCommentairesView
from usagers.views import LogoutView

urlpatterns = [
    path('', AccueilView.as_view(), name='accueil'),
    path('admin/', admin.site.urls),
    path('restaurants/', include("restaurants.urls"), name='restaurants'),
    path('login/',authentification_views.LoginView.as_view(template_name="usagers/login.html"),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('enregistrement/',include("usagers.urls")),
    path('mesCommentaires/', MesCommentairesView.as_view(), name='mesCommentaires'),
    path('administration/',AdministrationView.as_view(),name='administration'),
    path('captcha/', include('captcha.urls')),

]

restaurants/urls.py
from django.contrib import admin
from django.urls import include, path

from restaurants.views import AccueilRestaurant, DetailRestaurant, MesCommentairesView, ModifierRestaurantView, SupprimerRestaurantView, ModifierCommentaire, SupprimerCommentaireView

urlpatterns = [
    path('',AccueilRestaurant.as_view(), name="accueilRestaurant"),
    path('detailRestaurant/<str:pk>/', DetailRestaurant.as_view(), name='detailRestaurant'),
    path('ajouterCommentaire/<str:pk>/', DetailRestaurant.as_view(), name='ajouterCommentaire'),
    path('modifierCommentaire/<int:pk>/', ModifierCommentaire.as_view(), name='modifierCommentaire'),
    path('supprimerCommentaire/<int:pk>/', SupprimerCommentaireView.as_view(), name='supprimerCommentaire'),
    path('ajouterRestaurant/', AccueilRestaurant.as_view(), name='ajouterRestaurant'),
    path('modifierRestaurant/<str:pk>/', ModifierRestaurantView.as_view(), name='modifierRestaurant'),
    path('supprimerRestaurant/<str:pk>/', SupprimerRestaurantView.as_view(), name='supprimerRestaurant'), 
    path('mesCommentaires/', MesCommentairesView.as_view(), name='mesCommentaires'),

]

restaurants/models.py
import json
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.timezone import localtime

class TypeResto(models.Model):
    noType = models.AutoField(primary_key=True)
    nomType = models.CharField(max_length=20)

    def __str__(self):
        return self.nomType

class Restaurant(models.Model):
    noRestaurant = models.AutoField(primary_key=True)
    nomRestaurant = models.CharField(max_length=255) 
    villeRestaurant = models.CharField(max_length=25)
    imageRestaurant = models.URLField(default='https://example.com/default_image.jpg')
    typeRestaurant = models.ForeignKey(TypeResto, on_delete=models.DO_NOTHING)
    noteRestaurant = models.FloatField(null=True)
    adresseRestaurant = models.CharField(max_length=100, default="Inconnue")
    def __str__(self):
        return self.nomRestaurant

def update_note_restaurant(instance):
    avg_note = instance.commentaire_set.aggregate(avg_note=Avg('note'))['avg_note']
    avg_note_rounded = round(avg_note, 1) if avg_note is not None else 0
    instance.noteRestaurant = avg_note_rounded
    instance.save()

class Commentaire(models.Model):
    noCommentaire = models.AutoField(primary_key=True)
    noRestaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    userName = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    commentaire = models.TextField()
    note = models.IntegerField(default=0)
    dateCommentaire = models.DateField(auto_now_add=True)
    old_data = models.JSONField(null=True, blank=True) 

    def __str__(self):
        return f"{self.userName.username} - {self.noRestaurant.nomRestaurant} ({self.note})"

@receiver(post_save, sender=Commentaire)
def update_note_restaurant_on_commentaire_save(sender, instance, **kwargs):
    update_note_restaurant(instance.noRestaurant)

@receiver(post_delete, sender=Commentaire)
def update_note_restaurant_on_commentaire_delete(sender, instance, **kwargs):
    update_note_restaurant(instance.noRestaurant)
class Log(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    action = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)
    old_data = models.TextField(null=True, blank=True)
    new_data = models.TextField(null=True, blank=True)

    def __str__(self):
        local_timestamp = localtime(self.timestamp)
        formatted_time = local_timestamp.strftime("%d/%m/%Y %Hh%Mm%Ss")
        return f"{self.action} - {formatted_time}"

    def get_differences(self):
        old_data_dict = json.loads(self.old_data) if self.old_data else {}
        new_data_dict = json.loads(self.new_data) if self.new_data else {}

        differences = []
        for key, old_value in old_data_dict.items():
            new_value = new_data_dict.get(key)
            if old_value != new_value:
                differences.append(f"{key}: {old_value} -> {new_value}")

        return differences

restaurants/forms.py
from django import forms
from .models import Commentaire, TypeResto, Restaurant
from captcha.fields import CaptchaField


class CommentaireForm(forms.ModelForm):
    class Meta:
        model = Commentaire
        fields = ['commentaire', 'note']

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['nomRestaurant', 'villeRestaurant', 'adresseRestaurant', 'typeRestaurant']

class TypeRestoForm(forms.ModelForm):
    class Meta:
        model = TypeResto
        fields = ['nomType'] 
        widgets = {
            'nomType': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nomType'].label = 'Type de Restaurant'
        self.fields['nomType'].choices = [(type_resto.noType, type_resto.nomType) for type_resto in TypeResto.objects.all()]

class FormulaireAjoutRestaurant(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['nomRestaurant', 'villeRestaurant', 'typeRestaurant']
        widgets = {
            'nomRestaurant': forms.TextInput(attrs={'class': 'form-control'}),
            'villeRestaurant': forms.TextInput(attrs={'class': 'form-control'}),
            'adresseRestaurant': forms.TextInput(attrs={'class': 'form-control'}),
            'typeRestaurant': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['typeRestaurant'].queryset = TypeResto.objects.all()

class FormulaireModificationRestaurant(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['nomRestaurant', 'villeRestaurant', 'adresseRestaurant', 'typeRestaurant']
        widgets = {
            'nomRestaurant': forms.TextInput(attrs={'class': 'form-control'}),
            'villeRestaurant': forms.TextInput(attrs={'class': 'form-control'}),
            'adresseRestaurant': forms.TextInput(attrs={'class': 'form-control'}),
            'typeRestaurant': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['typeRestaurant'].queryset = TypeResto.objects.all()

class FormulaireSelectionRestaurant(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['villeRestaurant']
        widgets = {
            'villeRestaurant': forms.Select(attrs={'class': 'form-control'}),
        }

restaurants/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, View
from django.db.models import Avg, Q, F
from django.db.models.functions import Coalesce

from restaurants.forms import CommentaireForm, FormulaireModificationRestaurant, RestaurantForm
from restaurants.models import Commentaire, Restaurant, TypeResto

# Create your views here.
class AccueilRestaurant(ListView):
    model = Restaurant
    template_name = 'accueilRestaurant.html'
    context_object_name = 'lstRestaurants'

    def get_queryset(self):
        queryset = super().get_queryset()
        type_restaurant = self.request.GET.get('typeRestaurant')
        ville = self.request.GET.get('villeRestaurant')
        avec_note = self.request.GET.get('avecNote') == 'true'
        tri_note = self.request.GET.get('triNote') 

        if type_restaurant:
            queryset = queryset.filter(typeRestaurant__nomType=type_restaurant)
        
        if ville:
            queryset = queryset.filter(villeRestaurant__icontains=ville)
        
        if avec_note:
            queryset = queryset.exclude(noteRestaurant__isnull=True)

            
        if tri_note == 'asc':
            queryset = queryset.order_by('-noteRestaurant')
        elif tri_note == 'desc':
            queryset = queryset.order_by('noteRestaurant')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['villeSaisie'] = self.request.GET.get('villeRestaurant', '')
        context['typeRestaurants'] = TypeResto.objects.all()
        context['typeSaisi'] = self.request.GET.get('typeRestaurant', '')
        context['avecNote'] = self.request.GET.get('avecNote') == 'true'
        context['triNote'] = self.request.GET.get('triNote', '')  
        return context
    def post(self, request, *args, **kwargs):
        form = RestaurantForm(request.POST)
        if form.is_valid():
            form.instance.user = self.request.user
            form.save()
            return redirect('accueilRestaurant')
        else:

            return self.render_to_response(self.get_context_data(form=form))
    
class DetailRestaurant(DetailView):
    model = Restaurant
    template_name = 'detailRestaurant.html'
    context_object_name = 'leRestaurant'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Vérifier si l'utilisateur a déjà commenté ce restaurant
        user = self.request.user
        if user.is_authenticated:
            context['commentaire_exist'] = Commentaire.objects.filter(userName=user, noRestaurant=self.object).exists()
        context['commentaire_form'] = CommentaireForm() 
        return context

    def post(self, request, *args, **kwargs):
        restaurant = self.get_object()
        commentaire_form = CommentaireForm(request.POST)
        if commentaire_form.is_valid():
            nouveau_commentaire = commentaire_form.save(commit=False)
            nouveau_commentaire.userName = request.user
            nouveau_commentaire.noRestaurant = restaurant
            nouveau_commentaire.save()
            return redirect('detailRestaurant', pk=restaurant.pk)
        else:
            return self.render_to_response(self.get_context_data(commentaire_form=commentaire_form))

class ModifierRestaurantView(View):
    def get(self, request, pk):
        restaurant = get_object_or_404(Restaurant, pk=pk)
        form = FormulaireModificationRestaurant(instance=restaurant)
        context = {'form': form}
        return render(request, 'modifierRestaurant.html', context)

    def post(self, request, pk):
        restaurant = get_object_or_404(Restaurant, pk=pk)
        form = FormulaireModificationRestaurant(request.POST, instance=restaurant)
        if form.is_valid():
            form.instance.user = self.request.user
            form.save()
            return redirect('accueilRestaurant')
        context = {'form': form}
        return render(request, 'modifierRestaurant.html', context)

class SupprimerRestaurantView(View):
    def get(self, request, pk):
        restaurant = get_object_or_404(Restaurant, pk=pk)
        context = {'leRestaurant': restaurant}
        return render(request, 'supprimerRestaurant.html', context)

    def post(self, request, pk):
        restaurant = get_object_or_404(Restaurant, pk=pk)
        restaurant.delete()
        return redirect('accueilRestaurant')

class MesCommentairesView(View):
    def get(self, request):
        user = request.user
        
        commentaires = Commentaire.objects.filter(userName=user)
        print(commentaires)
        
        context = {'commentaires': commentaires}
        
        return render(request, 'mesCommentaires.html', context)
    
class ModifierCommentaire(UpdateView):
    model = Commentaire
    form_class = CommentaireForm
    template_name = 'modifierCommentaire.html'
    success_url = reverse_lazy('accueilRestaurant')

    def get(self, request, *args, **kwargs):
        commentaire = self.get_object()
        form = self.form_class(instance=commentaire)
        return render(request, self.template_name, {'form': form, 'commentaire': commentaire})

    def post(self, request, *args, **kwargs):
        commentaire = self.get_object()
        form = self.form_class(request.POST, instance=commentaire)
        if form.is_valid():
            form.instance.user = self.request.user
            form.save()
            return redirect(self.success_url, pk=commentaire.noRestaurant.pk)  # 
        return render(request, self.template_name, {'form': form, 'commentaire': commentaire})
    
class SupprimerCommentaireView(View):
    def get(self, request, pk):
        leCommentaire = get_object_or_404(Commentaire, pk=pk)
        context = {'leCommentaire': leCommentaire}
        return render(request, 'supprimerCommentaire.html', context)

    def post(self, request, pk):
        leCommentaire = get_object_or_404(Commentaire, pk=pk)
        leCommentaire.delete()
        return redirect('accueilRestaurant')

restaurants/templates/accueilRestaurant.html
{% extends 'maitre.html' %}
{% load static %}

{% block titre %}Critik - Restaurants{% endblock %}

{% block titrepage %}
<h2>Liste des restaurants</h2>
{% endblock %}

{% block restaurants %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row align-items-center">
                <div class="col-md-10">
                    <form class="row g-3" method="GET">
                        <div class="col-md-4">
                            <select class="form-select" name="typeRestaurant" id="typeRestaurant">
                                <option value="">Tous les types</option>
                                {% for type in typeRestaurants %}
                                <option value="{{ type.nomType }}" {% if type.nomType == typeSaisi %}selected{% endif %}>{{ type.nomType }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-4">
                            <input class="form-control" placeholder="Ville..." type="text" name="villeRestaurant" id="villeRestaurant" value="{{ villeSaisie }}">
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="btn" style="background-color: #d2b48c; color: #fff;">Filtrer</button>
                        </div>
                    </form>
                </div>

                {% if user.is_authenticated %}
                <div class="col-md-2 text-end">
                    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#ajouterRestaurantModal">
                        <i class="bi bi-plus"></i> Ajouter un restaurant
                    </button>
                </div>
                {% endif %}
            </div>
            
            <!-- Modal pour ajouter un restaurant -->
            <div class="modal fade" id="ajouterRestaurantModal" tabindex="-1" aria-labelledby="ajouterRestaurantModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="ajouterRestaurantModalLabel">Ajouter un restaurant</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form id="ajouterRestaurantForm" method="POST" action="{% url 'ajouterRestaurant' %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="nomRestaurant">Nom du restaurant:</label>
                                    <input type="text" class="form-control" id="nomRestaurant" name="nomRestaurant" required>
                                </div>
                                <div class="form-group">
                                    <label for="villeRestaurant">Ville:</label>
                                    <input type="text" class="form-control" id="villeRestaurant" name="villeRestaurant" required>
                                </div>
                                <div class="form-group">
                                    <label for="adresseRestaurant">Adresse:</label>
                                    <input type="text" class="form-control" id="adresseRestaurant" name="adresseRestaurant" required>
                                </div>
                                <div class="form-group">
                                    <label for="typeRestaurant">Type:</label>
                                    <select class="form-control" id="typeRestaurant" name="typeRestaurant" required>
                                        {% for type in typeRestaurants %}
                                            <option value="{{ type.pk }}">{{ type.nomType }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-primary">Ajouter</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Table des restaurants -->
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            Note
                            <a href="?triNote=asc"><i class="bi bi-arrow-up"></i></a>
                            <a href="?triNote=desc"><i class="bi bi-arrow-down"></i></a>
                        </th>
                        <th>Nom du Restaurant</th>
                        <th>Ville</th>
                        <th>Type</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for restaurant in lstRestaurants %}
                    <tr>
                        <td>{{ restaurant.noteRestaurant }} <i class="bi bi-star-fill text-warning"></i></td>
                        <td>{{ restaurant.nomRestaurant }}</td>
                        <td>{{ restaurant.villeRestaurant }}</td>
                        <td>{{ restaurant.typeRestaurant.nomType }}</td>
                        <td><a href="{% url 'detailRestaurant' restaurant.pk %}"><i class="bi bi-eye"></i></a></td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4">Aucun restaurant trouvé.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

restaurants/templates/detailRestaurant.html
{% extends 'maitre.html' %}
{% load static %}

{% block titre %}Critik - Détail du restaurant{% endblock %}

{% block titrepage %}
<h2>Restaurant choisi</h2>
{% endblock %}

{% block detailRestaurant %}
<div class="container mt-3">
    <div class="row">
        <div class="col-md-5">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h2>{{ leRestaurant.nomRestaurant }}</h2>
                    {% if user.is_authenticated and user.is_superuser %}
                    <div>
                        <a href="{% url 'modifierRestaurant' leRestaurant.pk %}" class="btn-icon"><i class="bi bi-pencil"></i></a>
                        <a href="{% url 'supprimerRestaurant' leRestaurant.pk %}" class="btn-icon"><i class="bi bi-trash"></i></a>
                        
                    </div>
                    {% endif %}
                </div>
                <div class="card-body">
                    <p><strong>Ville:</strong> {{ leRestaurant.villeRestaurant }}</p>
                    <p><strong>Adresse:</strong> {{ leRestaurant.adresseRestaurant }}</p>
                    <p><strong>Type:</strong> {{ leRestaurant.typeRestaurant.nomType }}</p>
                    {% if user.is_authenticated and not commentaire_exist %}
                    <a href="#" class="btn btn-primary" data-bs-toggle="modal"
                        data-bs-target="#ajouterCommentaireModal">Ajouter un commentaire</a>
                    {% endif %}
                </div>
            </div>

            <div class="modal fade" id="ajouterCommentaireModal" tabindex="-1"
                aria-labelledby="ajouterCommentaireModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="ajouterCommentaireModalLabel">Ajouter un commentaire</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form method="POST" action="{% url 'ajouterCommentaire' leRestaurant.pk %}">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label for="commentaire" class="form-label">Commentaire:</label>
                                    <textarea name="commentaire" id="commentaire" class="form-control" rows="3"
                                        required></textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="note" class="form-label">Note:</label>
                                    <input type="number" name="note" id="note" class="form-control" min="1" max="5"
                                        required>
                                </div>
                                <button type="submit" class="btn btn-primary">Envoyer</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Liste des commentaires</h5>
                    {% for commentaire in leRestaurant.commentaire_set.all %}
                    <div class="mb-3 p-3 border border-2 {% if commentaire.userName == user %}
                    custom-comment-highlight{% endif %}">
                        <p>
                            <strong>{{ commentaire.userName }}</strong>
                            {% if commentaire.userName == user %}
                                <a href="{% url 'modifierCommentaire' commentaire.pk %}"><i class="bi bi-pencil"></i></a>
                                <a href="{% url 'supprimerCommentaire' commentaire.pk %}"><i class="bi bi-trash"></i></a>
                            {% elif user.is_superuser %}
                                <a href="{% url 'supprimerCommentaire' commentaire.pk %}"><i class="bi bi-trash"></i></a>
                            {% endif %}
                        </p>
                        <p>{{ commentaire.commentaire }} </p>
                        <p><small>Note: {{ commentaire.note }} <i class="bi bi-star-fill text-warning"></i></small></p>
                    </div>
                    {% empty %}
                    <p>Aucun commentaire pour le moment.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

restaurants/templates/mesCommentaires.html
{% extends 'maitre.html' %}
{% load static %}
{% block titre %}Critik - Commentaires{% endblock %}

{% block titrepage %}
<h2>Listes des commentaires données aux restaurants</h2>
{% endblock %}
{% block historique %}
{% for c in commentaires %}
<div>
  <p><strong>{{ c.note }}<i class="bi bi-star-fill text-warning"></i></strong> pour le restaurant <strong>'{{ c.noRestaurant.nomRestaurant }}'</strong> situé à le '{{ c.noRestaurant.adresseRestaurant }}' <strong> le {{ c.dateCommentaire|date:"d F Y" }}</strong>: "{{ c.commentaire }}"</p> 
  </div>
{% endfor %}
{% endblock%}

restaurants/templates/modifierCommentaire.html
{% extends 'maitre.html' %}

{% block titre %}Critik - Modification d'un commentaire{% endblock %}

{% block formulaireAjout %} 
    <h4>Modification du commentaire choisi</h4>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Modifier</button>
    </form>


{% endblock %}

restaurants/templates/modifierRestaurant.html
{% extends 'maitre.html' %}
{% load widget_tweaks %}

{% block titre %}Critik - Modification d'un restaurant{% endblock %}

{% block formulaireAjout %} 
<h4 class="mb-4">Modification du restaurant choisi</h4>
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_nomRestaurant" class="form-label">Nom du restaurant</label>
        {{ form.nomRestaurant|add_class:"form-control" }}
    </div>
    <div class="mb-3">
        <label for="id_villeRestaurant" class="form-label">Ville</label>
        {{ form.villeRestaurant|add_class:"form-control" }}
    </div>
    <div class="mb-3">
        <label for="id_adresseRestaurant" class="form-label">Adresse</label>
        {{ form.adresseRestaurant|add_class:"form-control" }}
    </div>
    <div class="mb-3">
        <label for="id_typeRestaurant" class="form-label">Type</label>
        {{ form.typeRestaurant|add_class:"form-select" }}
    </div>
    <button type="submit" class="btn btn-primary">Modifier</button>
</form>
{% endblock %}

restaurants/templates/supprimerCommentaire.html
{% extends 'maitre.html' %}
{% block titre %}Critik - Suppression du commentaire{% endblock %}

{% block titrepage %}
    <p>Supprimer un commentaire</p>
{% endblock %}


{% block ConfirmationFormulaire %}
  <form method="POST">
    {% csrf_token %}
    <p>Voulez-vous supprimer le commentaire "{{ leCommentaire.commentaire }}" avec la note de "{{leCommentaire.note }} étoiles" ? </p>
    <p style="text-align: center;"><input type="submit" value="Oui"></p>
  </form>
  <p style="text-align: center;"><a href="{% url 'accueilRestaurant' %}">Annuler et retour à la page des restaurants</a></p>
{% endblock %}

restaurants/templates/supprimerRestaurant.html
{% extends 'maitre.html' %}
{% block titre %}Cinéma - Suppression de la réservation{% endblock %}

{% block titrepage %}
    <p>Supprimer une réservation</p>
{% endblock %}


{% block ConfirmationFormulaire %}
  <form method="POST">
    {% csrf_token %}
    <p>Voulez-vous supprimer le restaurant {{ leRestaurant.nomRestaurant }} ? </p>
    <p style="text-align: center;"><input type="submit" value="Oui"></p>
  </form>
  <p style="text-align: center;"><a href="{% url 'accueilRestaurant' %}">Annuler et retour à la page des restaurants</a></p>
{% endblock %}